version: '2'

services:

 proxy:
  image: vimagick/dante
  restart: always
  ports:
   - "1080:1080"

 nodepki:
  image: adito/nodepki-docker
  volumes:
   - ./nodepki/root.cert.pem:/root/nodepki-webclient/data/mypki/root/root.cert.pem:rw
   - ./nodepki/conf/http_server.conf:/etc/supervisor/conf.d/http_server.conf
   - ./docker-nodepki/applications/nodepki/data/config:/root/nodepki/data/config
   - ./docker-nodepki/applications/nodepki-client/data/config:/root/nodepki-client/data/config
   - ./docker-nodepki/applications/nodepki-webclient/data/config:/root/nodepki-webclient/data/config
   - ./docker-nodepki/applications/nodepki-webclient/api/webclient/controllers/request.js:/root/nodepki-webclient/controllers/request.js
   - nodepki-data:/root/nodepki/data
   - nodepki-data:/root/nodepki-client/data
   - nodepki-data:/root/nodepki-webclient/data
   - nodepki-certs-nexus:/certs/nexus
   - nodepki-certs-gitlab:/certs/gitlab
   - nodepki-certs-gitlab-runner-01:/certs/gitlab-runner-01
  environment:
   - API_USERNAME=${API_USERNAME}
   - API_PASSWORD=${API_PASSWORD}

 nexus:
  image: clearent/nexus:latest
  restart: always
  volumes:
   - nexus-data:${NEXUS_DATA}
   - nexus-back:/backup
   - nodepki-certs-nexus:/certs/nexus
   - ./nexus/etc/nexus.properties:/nexus-data/etc/nexus.properties
  environment:
   - JKS_PASSWORD=${JKS_PASSWORD}

 gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab'
# ports:
#   - '8443:8443'
#   - '9418:22'
  volumes:
    - 'gitlab-log:/var/log/gitlab'
    - 'gitlab-data:/var/opt/gitlab'
    - nodepki-certs-gitlab:/etc/gitlab/ssl
    - ./trusted:/etc/gitlab/trusted-certs

 gitlab-dind:
  image: docker:17.06.0-ce-dind
  privileged: true
  restart: always
  volumes:
   - dind-data:/var/lib/docker

 gitlab-runner:
  image: gitlab/gitlab-runner:alpine
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./gitlab-runner/config:/etc/gitlab-runner
   - ./extras:/usr/share/ca-certificates/extra
   - ./certs:/etc/ssl/certs
  environment:
   - DOCKER_HOST=tcp://gitlab-dind:2375

volumes:
 gitlab-log:
 gitlab-data:
 dind-data:
 nexus-data:
 nexus-back:
 nodepki-root:
 nodepki-data:
 nodepki-certs-nexus:
 nodepki-certs-gitlab:
 nodepki-certs-gitlab-runner-01:
