version: '2'

services:

 proxy:
  image: vimagick/dante
  restart: always
  ports:
   - "1080:1080"
  logging:
   options:
    max-size: 50m
    
 nodepki:
  image: adito/nodepki-docker
  volumes:
   - ./nodepki/data:/root/nodepki/data
   - ./nodepki/data:/root/nodepki-client/data
   - ./nodepki/data:/root/nodepki-webclient/data

   - ./docker-nodepki/applications/nodepki/data/config:/root/nodepki/data/config
   - ./docker-nodepki/applications/nodepki-client/data/config:/root/nodepki-client/data/config
   - ./docker-nodepki/applications/nodepki-webclient/data/config:/root/nodepki-webclient/data/config
   - ./docker-nodepki/applications/nodepki-webclient/api/webclient/controllers/request.js:/root/nodepki-webclient/controllers/request.js
   - ./conf/http_server.conf:/etc/supervisor/conf.d/http_server.conf

   - nodepki-certs-nexus:/certs/nexus
   - nodepki-certs-gitlab:/certs/gitlab
   - nodepki-certs-gitlab-runner-01:/certs/gitlab-runner-01
  environment:
   - API_USERNAME=${API_USERNAME}
   - API_PASSWORD=${API_PASSWORD}
  logging:
   options:
    max-size: 50m
    
 nexus:
  image: clearent/nexus:latest
  restart: always
  expose:
   - "443"
  cap_add:
   - NET_BIND_SERVICE
  volumes:
   - nexus-data:${NEXUS_DATA}
   - nexus-back:/backup
   - nodepki-certs-nexus:/certs/nexus
   - ./nexus/etc/nexus.properties:/nexus-data/etc/nexus.properties
  environment:
   - JKS_PASSWORD=${JKS_PASSWORD}
  logging:
   options:
    max-size: 50m
    
 gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab'
# ports:
#   - '8443:8443'
#   - '9418:22'
  volumes:
    - 'gitlab-log:/var/log/gitlab'
    - 'gitlab-data:/var/opt/gitlab'
    - nodepki-certs-gitlab:/etc/gitlab/ssl
    - ./trusted:/etc/gitlab/trusted-certs
  logging:
   options:
    max-size: 50m
    
 gitlab-dind:
  image: docker:17.06.0-ce-dind
  privileged: true
  restart: always
  volumes:
   - dind-data:/var/lib/docker
  logging:
   options:
    max-size: 50m
    
 gitlab-runner:
  image: gitlab/gitlab-runner:alpine
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./gitlab-runner/config:/etc/gitlab-runner
   - ./gitlab-runner/daemon.json:/etc/docker/daemon.json
   - ./extra:/usr/local/share/ca-certificates
   - ./keys/root.cert:/etc/ssl/certs/ca-certificates.crt
   - ./ssl:/ssl
# environment:
#  - DOCKER_HOST=tcp://gitlab-dind:2375
  logging:
   options:
    max-size: 50m

volumes:
 gitlab-log:
 gitlab-data:
 dind-data:
 nexus-data:
 nexus-back:
 nodepki-root:
 nodepki-data:
 nodepki-certs-nexus:
 nodepki-certs-gitlab:
 nodepki-certs-gitlab-runner-01:
